name: RamadhanEvent
version: '1.0-SNAPSHOT'
main: my.pikrew.ramadhanEvent.RamadhanEvent
api-version: '1.21'
author: 'Pikrew, Bintanq'

commands:
  ramadhan:
    description: Main RamadhanEvent command (time, crate box, wand, reload, debug).
    usage: /ramadhan <reload|debug|box|wand>
    aliases: [re, ramadan]

  ramadhanintegrationmobs:
    description: Ramadhan Integration Mobs command
    usage: /ramadhanintegrationmobs [status|refresh|mobs|scan|test]
    permission: ramadhanevent.admin

  netherspawntest:
    description: Test the nether spawn system — clears mobs, forces a phase, runs cycles, reports locations.
    usage: /netherspawntest <day|night> <cycles>
    permission: ramadhanevent.admin

permissions:

  ramadhan.reload:
    description: Reload the RamadhanEvent configuration.
    default: op
  ramadhan.debug:
    description: View debug information.
    default: op

  ramadhan.crate.admin:
    description: Full access to /ramadhan box.
    default: op

  ramadhan.wand.use:
    description: Use the region wand to select positions.
    default: op
  ramadhan.wand.give:
    description: Receive the region wand item.
    default: op
  ramadhan.wand.save:
    description: Save a selected region as the crate spawn zone.
    default: op
  ramadhan.wand.reset:
    description: Reset wand position selections.
    default: op

  ramadhanevent.admin:
    description: Access to /ramadhanintegrationmobs and /netherspawntest.
    default: op