name: RamadhanEvent
version: '1.0-SNAPSHOT'
main: my.pikrew.ramadhanEvent.RamadhanEvent
api-version: '1.21'

commands:
  ramadhan:
    description: Main RamadhanEvent command (time, crate box, wand, reload, debug).
    usage: /ramadhan <reload|debug|box|wand>
    aliases: [re, ramadan]

  ramadhanintegrationmobs:
    description: Ramadhan Integration Mobs command
    usage: /ramadhanintegrationmobs [status|refresh]
    permission: ramadhanevent.admin

permissions:

  # --- Ramadhan time ---
  ramadhan.reload:
    description: Reload the RamadhanEvent configuration.
    default: op
  ramadhan.debug:
    description: View debug information.
    default: op

  # --- Crate admin ---
  ramadhan.crate.admin:
    description: Full access to /ramadhan box.
    default: op

  # --- Wand ---
  ramadhan.wand.use:
    description: Use the region wand to select positions.
    default: op
  ramadhan.wand.give:
    description: Receive the region wand item.
    default: op
  ramadhan.wand.save:
    description: Save a selected region as the crate spawn zone.
    default: op
  ramadhan.wand.reset:
    description: Reset wand position selections.
    default: op

  # --- Mobs integration ---
  ramadhanevent.admin:
    description: Access to /ramadhanintegrationmobs.
    default: op